// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Caml_oo_curry = require("bs-platform/lib/js/caml_oo_curry.js");
var SuperMemo$SuperMemo = require("../src/SuperMemo.bs.js");

Jest.describe("SuperMemo Algoritmn", (function (param) {
        return Jest.describe("Easiness Factor", (function (param) {
                      Jest.test("Let easiness factor equal 1.3 when less than 1.3", (function (param) {
                              var response = SuperMemo$SuperMemo.calculate(3, 1, 1.2);
                              return Jest.Expect[/* toEqual */12](1.3, Jest.Expect[/* expect */0](Caml_oo_curry.js1(-231258312, 1, response)));
                            }));
                      Jest.test("When quality increases, increase the easiness factor", (function (param) {
                              var response = SuperMemo$SuperMemo.calculate(5, 1, 1.5);
                              return Jest.Expect[/* toEqual */12](1.6, Jest.Expect[/* expect */0](Caml_oo_curry.js1(-231258312, 2, response)));
                            }));
                      return Jest.test("When quality decreases, decrease the easiness factor", (function (param) {
                                    var response = SuperMemo$SuperMemo.calculate(1, 1, 2.5);
                                    return Jest.Expect[/* toEqual */12](1.96, Jest.Expect[/* expect */0](Caml_oo_curry.js1(-231258312, 3, response)));
                                  }));
                    }));
      }));

/*  Not a pure module */
